apiVersion: v1
kind: Namespace
metadata:
  name: banana
  labels:
    name: banana
# use --- to split different k8s resources
---
apiVersion: v1
kind: Namespace
metadata:
  name: radar
  labels:
    name: radar
---
apiVersion: v1
kind: Namespace
metadata:
  name: uss
  labels:
    name: uss
