apiVersion: v1
kind: Service
metadata:
  name: create-react-app
spec:
  ports:
    - name: http
      port: 3000 # exposed port
      targetPort: 80 # Pod port
  selector:
    app: create-react-app # targeted Pods' label
